# Generated by Django 4.1.3 on 2023-04-03 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tableau", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tache",
            name="col_task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tableau.colonne",
            ),
        ),
    ]
